### PR TITLE
add framework targets

### PR DESCRIPTION
**Pull request by vilinski**
- add `netcoreapp3.1` and `net5.0` targets for the case when no other frameworks are installed on the machine
- fix obsolete project tags
- fix a typo in readme

### CODE REVIEW

**Comment by Krzysztof-Cieslak** [comment]
Thanks!

**Comment by slang25** [comment]
Any chance of a new release, I'm building from source every time I set up a new laptop (for the `--bin` functionality)

**Comment by vilinski** [comment]
https://twitter.com/dsymetweets/status/1333818089809580035

**Comment by nojaf** [comment]
Hey Kris, were you ever able to release this?

**Comment by Krzysztof-Cieslak** [comment]
1.0.2 released

**Comment by slang25** [comment]
Thanks @Krzysztof-Cieslak 🙂

**Pull request merged**
